# Lab 3 — Ansible Inventory
# Master VM1 controls the managed nodes below.

[managed_nodes]
# VM2 — the managed node with Docker + static containers
lab3-node ansible_host=192.168.58.11 ansible_user=vagrant

[static_containers]
# Static containers running on VM2 (managed through docker connection)
static-nginx ansible_host=192.168.58.11 ansible_user=vagrant ansible_connection=docker
static-httpd ansible_host=192.168.58.11 ansible_user=vagrant ansible_connection=docker

[all:vars]
ansible_python_interpreter=/usr/bin/python3
